### ISSUE TITLE
linux can't make

### ISSUE THREAD

**Issue by Yurri-huang** [gdt050579/AppCUI#429]
**Desktop (please complete the following information):**
 - OS: [Deepin OS V20]
 - AppCUI Version [branch master]

**Describe the bug**
![image](https://github.com/gdt050579/AppCUI/assets/34232854/1e87fa1a-14a3-4a93-9594-13d47a10ae05)

**Comment by Yurri-huang** [comment]
![image](https://github.com/gdt050579/AppCUI/assets/34232854/1d7375d0-72e4-498f-9ce4-d0086bbb5bde)
![image](https://github.com/gdt050579/AppCUI/assets/34232854/487f2cc4-bcb7-4fe7-bfcf-40d1d235dfe1)

**Comment by gheorghitamutu** [comment]
Hello, @Yurri-huang,

Please attach the log for `AppCUI/build/vcpkg-bootstrap.log`.

Usual the problem is self-explanatory in the log, for example:


root@e949772cd302:/home/repo/AppCUI# cat /home/repo/AppCUI/build/vcpkg-bootstrap.log
Could not find curl. Please install it (and other dependencies) with:
On Debian and Ubuntu derivatives:
  sudo apt-get install curl zip unzip tar
On recent Red Hat and Fedora derivatives:
  sudo dnf install curl zip unzip tar
On older Red Hat and Fedora derivatives:
  sudo yum install curl zip unzip tar
On SUSE Linux and derivatives:
  sudo zypper install curl zip unzip tar
On Arch Linux and derivatives:
  sudo pacman -S curl zip unzip tar cmake ninja
On Alpine:
  apk add build-base cmake ninja zip unzip curl git
  (and export VCPKG_FORCE_SYSTEM_BINARIES=1)
